name: CI Deploy Hugo Blog

on:
  push:
    branches:
      - main  # Run this workflow when pushing to main

permissions:
  contents: write # GitHub Actions runs with read-only permissions by default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.14.0  # Set the Node version you need

      - name: Install Dependencies
        run: npm install  # Only if you have Node dependencies

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: hugo --baseURL "https://zhad2025.github.io/zhadblog/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo's output folder